version: '3'
services:
  frontend-webapp:
    build: frontend-webapp
    ports:
      - "8001:8001"
    volumes:
      - ./frontend-webapp:/app
    depends_on:
      - conv-backend-chatterbot
    environment:
      API_URL_BASE: 'http://conv-backend-chatterbot'

  conv-backend-chatterbot:
    build: conv-backend-chatterbot
    ports:
      - "8002:80"
    command: /start-reload.sh
    volumes:
      - ./conv-backend-chatterbot/app:/app
    depends_on:
      - mongodb
    environment:
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_DATABASE: $MONGO_DATABASE

  mongodb:
    image: mongo:4.2-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
    volumes:
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - mongo:/data/db

volumes:
  mongo: