version: '3'
services:
  frontend-webapp:
    build: frontend-webapp
    volumes:
      - ./frontend-webapp:/app
    depends_on:
      - conv-backend-adaptor

  conv-backend-adaptor:
    build: conv-backend-adaptor
    command: /start-reload.sh
    volumes:
      - ./conv-backend-adaptor/app:/app
    environment:
      BACKEND_CHATTERBOT_URL: http://conv-backend-chatterbot
      BACKEND_ECHO_URL: http://conv-backend-echo
      BACKEND: echo

  # conv-backend-chatterbot:
  #   build: conv-backend-chatterbot
  #   command: /start-reload.sh
  #   volumes:
  #     - ./conv-backend-chatterbot/app:/app
  #   depends_on:
  #     - mongodb
  #   environment:
  #     MONGO_USERNAME: $MONGO_USERNAME
  #     MONGO_PASSWORD: $MONGO_PASSWORD
  #     MONGO_DATABASE: $MONGO_DATABASE

  conv-backend-echo:
    build: conv-backend-echo
    command: /start-reload.sh
    volumes:
      - ./conv-backend-echo/app:/app

  # mongodb:
  #   image: mongo:4.2-bionic
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #     MONGO_INITDB_USERNAME: $MONGO_USERNAME
  #     MONGO_INITDB_PASSWORD: $MONGO_PASSWORD
  #     MONGO_INITDB_DATABASE: $MONGO_DATABASE
  #   volumes:
  #     - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
  #     - mongo:/data/db

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8001:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      #- conv-backend-chatterbot
      - conv-backend-echo
      - frontend-webapp

volumes:
  mongo: