version: "3"
services:
  frontend-webapp:
    build: frontend-webapp
    volumes:
      - ./frontend-webapp:/app
    depends_on:
      - correction-adaptor

  correction-backend-echo:
    build: correction-backend-echo
    command: /start-reload.sh
    volumes:
      - ./correction-backend-echo/app:/app

  correction-adaptor:
    build: correction-adaptor
    command: /start-reload.sh
    volumes:
      - ./correction-adaptor:/app
    ports:
      - 8002:80
    environment:
      BACKEND_ECHO_URL: http://correction-backend-echo
      BACKEND: echo

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8001:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - correction-adaptor
      - frontend-webapp

volumes:
  mongo:
