apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-backend-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conv-backend-echo
      tier: backend
  template:
    metadata:
      labels:
        app: conv-backend-echo
        tier: backend
    spec:
      containers:
        - name: conv-backend-echo
          image: conv-backend-echo:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: conv-backend-echo
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: conv-backend-echo
    tier: backend
